import { Montserrat } from "next/font/google";
import "./ui/globals.css";
import Navbar from "./ui/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "BOD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}