import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./ui/globals.css";
import Navbar from "./ui/Navbar"

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BOD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
